### ISSUE TITLE
Please add geopoliticalfutures

### ISSUE THREAD

**Issue by inteloperator** [iamadamdev/bypass-paywalls-chrome#100]
geopoliticalfutures.com

**Comment by iamadamdev** [comment]
New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.
