### ISSUE TITLE
Seeking Alpha not working

### ISSUE THREAD

**Issue by adrianshlai** [iamadamdev/bypass-paywalls-chrome#1023]
Hi,

It seems like seeking alpha's premium content is not working. I'm brought to a captcha to prove I'm not a robot. After clicking hold it does not redirect to the article. 

![image](https://user-images.githubusercontent.com/20070403/99216790-930aa400-27a4-11eb-9da2-ec38f7d971f5.png)

**Comment by iamadamdev** [comment]
article url?

**Comment by adrianshlai** [comment]
https://seekingalpha.com/article/4378215-opendoor-play-on-future-of-real-estate-services

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/99300292-40130a00-2801-11eb-9e9a-856d644c8fa0.png)

**Comment by storagenerd12** [comment]
I see this issue too, after press and hold keep getting error of Please Try again, here is the link 

https://seekingalpha.com/article/4388442-laurentian-bank-5_5-dividend-yield-while-trading-just-9x-earnings?source=feed_tag_editors_picks

**Comment by iamadamdev** [comment]
Worked after pressing and holding, it redirects to the correct page for me:
![image](https://user-images.githubusercontent.com/36013816/99312530-077c2c00-2813-11eb-8380-fd47d8db078d.png)

**Comment by storagenerd12** [comment]
I am not sure what is wrong, I updated to the latest code base just in case. Restarted chrome too, after pressing and holding here is what I get 

![image](https://user-images.githubusercontent.com/67955142/99326367-0952e900-282d-11eb-815a-27695dbe3c32.png)

**Comment by davidszpak** [comment]
I had the same problem. After numerous tests in incognito mode vs. normal mode and disabling all extensions, it appears cookies were the problem.

In order to clean up cookies, I used the "edit this cookie" extension (available at https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg) - Goto seekingalpha, and remove all saved cookies for seekingalpha.com. Then retry loading your desired page with bypass-paywalls-chrome again. Worked for me now.

**Comment by adrianshlai** [comment]
Yes - this solution works. Thanks!
