### ISSUE TITLE
Added ynet+

### ISSUE THREAD

**Issue by MrTal** [iamadamdev/bypass-paywalls-chrome#116]
Hו
maybe can added this site: https://premium.ynet.co.il/Web/Manage/Main?
new service the news  Premium paywalls
exmple: https://www.ynet.co.il/articles/0,7340,L-5460963,00.html
tank you

**Comment by iamadamdev** [comment]
New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.

**Comment by MrTal** [comment]
@iamadamdev 
Hi
this not work in new incognito window, not have what do with this?
also in  Firefox?

**Comment by iamadamdev** [comment]
New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.

That is a hard paywall.
