### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by encikkeju** [iamadamdev/bypass-paywalls-chrome#198]
I'm all good loading this up on desktop chrome, but struggle to do it on Android using kiwi browser (which supports extensions).  Any tips on how to load on to Android kiwi browser?

Thanks!

**Comment by iamadamdev** [comment]
Why not use the official Google Chrome along with uBlock Origin?

**Comment by encikkeju** [comment]
Hi Adam

Chrome works well on desktops - easy to add extensions - and this is what I
use.  Unfortunately Chrome mobile (eg Android browser) doesn't allow
extensions, but the new Kiwi browser does.

I hope this helps.  My prefer would be to use chrome on my phone if it
allowed for extensions.

**Comment by iamadamdev** [comment]
I haven't tried the kiwi browser. You can also use it on Firefox for Android and it works flawlessly there, and auto-updates work too!
https://github.com/iamadamdev/bypass-paywalls-firefox

**Comment by encikkeju** [comment]
Ah, great! Thanks, will give it a go

**Comment by Safekeep** [comment]
To load this on Kiwi browser, you'll need to load the unpacked version on a Chrome desktop browser, then click on "Pack Extension", choose the folder, then click on the "Pack Extension" button.  This will create a "bypass-paywalls-chrome-master.crx" file, which can then be copied to your android phone and loaded into the Kiwi browser... Everything seems to work except for "wired.com"... It still detects that you are not signed in and will complain after the 2nd article until you manually clear cookies again... Not sure why this issue is appearing on Kiwi but not on Chrome on the desktop...
