### ISSUE TITLE
Need to reload this bypass extension every time when open Chrome

### ISSUE THREAD

**Issue by GuanshengDu** [iamadamdev/bypass-paywalls-chrome#229]
Everytime when I close all Chrome tabs and reopen the Chrome, the Bypass extension is lost. I need to reload this extension every time. Is it only my problem or anyone has the same problem?
Chrome, 74.0.3729.169, 64bit. Windows 7

**Comment by Pike-Tar** [comment]
It's happening to me too.

**Comment by iamadamdev** [comment]
Did you enable developer mode?
And follow all the instructions here:
https://github.com/iamadamdev/bypass-paywalls-chrome#installation-instructions

**Comment by GuanshengDu** [comment]
> Did you enable developer mode?
> And follow all the instructions here:
> https://github.com/iamadamdev/bypass-paywalls-chrome#installation-instructions

Hi Adam, thanks for your reply. I followed all the instructions as recommended, but this problem is still. I used your extension on two computers. I can see the difference is the OS. My Chrome on Win7 has this problem, but on other computer with Win10 does not have this problem.

**Comment by iamadamdev** [comment]
Unfortunately I don't have any solution for Windows 7.

**Comment by spookyUnknownUser** [comment]
I don't know if this would be useful, but it is possible to add an extension whitelist to windows registory so that chrome ignores whitelists sideloaded extensions, see [here](https://smartbear-cc.force.com/portal/KbArticleViewer?name=How-do-I-whitelist-an-extension-in-Chrome-if-Chrome-Web-Store-is-blocked-in-our-company&sp=testcomplete).

So with a small .reg script like the following, we should be able to make chrome ignore th extension: 
```reg
Windows Registry Editor Version 5.00
; https://stackoverflow.com/a/48990515/1649917
; Unpack extension and install in Chrome then double click .reg file 

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\ExtensionInstallWhitelist]
"1"="efboiahoapapjihilfiilldiamdjjlol"
```

That is, it worked for me at least. Though you do get this ribbon on your setting that chrome is being controlled by your organisation :/

**Comment by vic958420** [comment]
This extension keeps on uninstalling itself after closing Chromium on Ubuntu 19.04 and I have to constantly reinstall the extension.
