### ISSUE TITLE
Latest version of this extension keeps uninstalling itself upon closing the browser on windows 10

### ISSUE THREAD

**Issue by vic958420** [iamadamdev/bypass-paywalls-chrome#247]
Whenever I close chrome on windows 10, the bypass paywalls extensions gets automatically uninstalled and I have to reinstall the extension every time. This issue seems to have been caused by the last few commits made to the extension.

**Comment by DNohlen** [comment]
I can confirm this although I am using the extension at the new Microsoft Edge (Chrome-based) browser.

**Comment by gkrawiec** [comment]
i have the same problem but chrome on macos.

**Comment by iamadamdev** [comment]
Every time you open Chrome it may warn you about running extensions in developer mode, just click 🗙 to keep the extension enabled.

Still works fine for me on Windows 10.

**Comment by gkrawiec** [comment]
seems like the issue is that chrome depends on the specifci extension installer folder.
I download the zip file to my Downloads folder and unzip right there in the downloads.
I install by moving that folder into the extensions page in chrome. If I then delete the installer files from the Downloads folder the extension is removed from chrome.
At least that is what it seems. I am leaving the folder there this week. I will see if it uninstalls.
