### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by padiauj** [iamadamdev/bypass-paywalls-chrome#293]
Please remove the following google analytics tracking from this extension, or at least tell people that you are tracking them when they install this extension

https://github.com/iamadamdev/bypass-paywalls-chrome/blob/0c742f82b049fca61157956c041b786ae5ba6142/background.js#L354-L362

**Comment by iamadamdev** [comment]
No personally identifiable information is revealed. This is harmless. It is simply to see how many people are using this. If no one uses this I'm not going to spend my time updating it.

**Comment by jsEveryDay** [comment]
The issue is that its not just for you, and its not just you seeing that data. I would totally allow it if it was your tracker, on your server with your name behind it. When you GA in an extension the cookies remain permanently. Try this in your chorme with the right permissions,

`chrome.cookies.getAll(
    {
        name: '_ga',
        session: false
    },
    v => {
        v.forEach(e => {
console.log(e.domain); /// see how many _GA's you have on your browser, also if you proceed with the following code, look what happens... see how google goes nuts. So is not just for your own tracking purposes. Tired of having to clean up your code and many other extensions out there. Id rather see piwik or stupid kiddie stuff like that then GA.
            var newCookie = {
                url: 'http://' + e.domain.slice(1),
                domain: e.domain,
                name: '_ga',
                value: 'GA0'
            };
            chrome.cookies.set(newCookie, c => {
                if (!c) {
                    console.log('Error: ' + e.domain);
                } else {
                    console.log('done');
                }
            });
        });
    }
);`
I've emailed this to at least 20ppl, everybody in the office has it and I have to maintain it every time, cuz you need your GA. 
Either do it because you are good people or don't. What difference does it make how many use it?
Anyways, WSJ is done since monday, so now it's useless and I know you cant fix it, I spoke with a news corp guy and they were very well aware of your repo. Keep watching the stats, I guess it makes you feel good and it alerts google which in turn notifies companies who doesn't have competition with but buy ads in there. All in all, f tracking. Tired of keeping up with DNS blocks, so tired, why cant the world be nice and green like my jenkins box. :P

**Comment by iamadamdev** [comment]
There is no GA tracking in my Firefox extension, feel free to use that one.
https://github.com/iamadamdev/bypass-paywalls-firefox

Also comes with automatic updates!

**Comment by london617** [comment]
@jsEveryDay 
Use https://github.com/magnolia1234/bypass-paywalls-chrome-clean
