### ISSUE TITLE
NYT and Chrome 77

### ISSUE THREAD

**Issue by pal2002** [iamadamdev/bypass-paywalls-chrome#338]
NYTimes stopped working with Chrome 77 update with 1.5.4. I do not have ublock, previously NYT worked with only this extension. Bypassing works on all other sites.

Looks like this was previously mentioned here
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/235

Firefox with latest add on version works.

**Comment by iscreamcoke** [comment]
See the [tutorial](https://github.com/iamadamdev/bypass-paywalls-chrome/issues/347)

**Comment by rpodric** [comment]
Does the above possibly relate to a relatively new issue with NYT (seemingly Chrome only) in which URLs starting with "interactive," like this one:

`https://www.nytimes.com/interactive/2019/10/15/us/elections/debate-speaking-time.html`

are blocked, coming up with a "Keep reading The Times by creating a free account or logging in" message that prevents you from seeing the article?

Note that I'm speaking here only of _once you've exceeded your free article count_, not before. If you clear NYT cookies to reset the count, you _can_ view "interactive" articles until you hit the count again.

All links without "interactive" at the start of the URL work fine regardless of count and without worrying about cookies, so it's a very specific issue with just those kind of URLs, which are in the definite minority of URLs on that site, thankfully.

**Comment by iscreamcoke** [comment]
There shouldn’t be an issue: the NYT address is not changed, only the subdomain. I’ll look into that this weekend

**Comment by magnolia1234** [comment]
Works just fine for me (also without uBlock Origin).

**Comment by rpodric** [comment]
Do you mean in general or /interactive articles?

I think you'll find that certain /interactive articles, like the one above, will [stop working](https://i.imgur.com/CUquyL6.png) (at least in Chrome/Chromium) once you hit a certain number of read articles without deleting nytimes.com cookies.

Neither uBO nor the extension seem to get around that at this point. It's unclear to me which of the two had been getting around it before this started some weeks ago, since I use both.

**Comment by magnolia1234** [comment]
Works for me in the EU with this extension (clears local storage) and also without uBlock Origin.
Just a 'Continue to your one article'-banner at the bottom.
Clearing cookies is also an extra possibility in this extension, but so far no need (for me).

**Comment by subiedubie** [comment]
I've been having the same issue as Pal2002.

I keep getting the "Keep reading the Times by creating a free account...." otherwise I can't read the article. The extension works on other sites. This is recent with the new Chrome update. I also have uBlock installed. 

Fixes: (1) clear cookies and it works (annoying but works)
(2) tried updating files as suggested (hasn't worked)

This issue is for non "/interactive" articles. It happens on all of them.

Insights or advice? Many thanks.

**Comment by magnolia1234** [comment]
uBlock Origing blocks the 'This is your one article preview. Read more articles each month with a free account.' which you can also close by hand though.
Are you using latest BP v1.5.6?

**Comment by rpodric** [comment]
I haven't been seeing that in 1.5.5 or 1.5.6, so I can't explain what subiedubie is seeing.

BTW, 1.5.6 will read as 1.5.5, since the file(s) that controls that wasn't updated. Not really important, but I just mention it to avoid confusion.
