### ISSUE TITLE
Extension disappearing from Chrome!

### ISSUE THREAD

**Issue by SanFranciscoAntiGenfrifier** [iamadamdev/bypass-paywalls-chrome#401]
Twice now recently I have gone to use the extension, found it is not working, checked my extensions, and found it missing!

Is Google removing this extension?

I am going to add it back again now and see if it disappears again!

**Comment by magnolia1234** [comment]
No, Chrome shouldn't do this ...
Extension is completely removed or 'just' icon from toolbar?

**Comment by SanFranciscoAntiGenfrifier** [comment]
I did not check the icon, but it disappeared twice from the installed
Extensions page.

It is still there this AM.

Thank you.

**Comment by SanFranciscoAntiGenfrifier** [comment]
Is there anyway to automatically update these?

The one for Firefox says June and no longer works!

**Comment by nicolamano** [comment]
I had the same issue in chrome (for macos). 
Try to install the extension and trigger a sync of chrome with your google account before closing the browser.

**Comment by magnolia1234** [comment]
Both Chrome and Firefox should update automatically.
Maybe remove extension and reinstall?

**Comment by bigpoppapaul** [comment]
I'm having the exact same issue, every time I close chrome fully, the extension is uninstalled.

**Comment by jack94707** [comment]
In my case the solution was simple. I installed the extension as directed and after installation would delete the installation zip file and folder. Sure enough, the extension would disappear on each browser start. 

Then I noticed in the extension details that the "Source" was listed as the location of the "bypass-paywalls-chrome-master" file. I reasoned that the extension would load from there, and I think it does at every browser start-up. So before I re-installed it, I moved the source folder to a permanent location and then dragged it over the extensions page to install it.

It has never disappeared since. You need to leave the source folder in place after installation.

I think this subtlety needs to be included in the installation instructions. You can see I'm not the only one who fell into this trap, and I won't be the last.

**Comment by magnolia1234** [comment]
Indeed no copy of folder is made, so hold on to the original extension folder.
Advantage is that you can edit the BP files directly (and use after refresh/reload BP in extensions).
