### ISSUE TITLE
Financial Times stopped working

### ISSUE THREAD

**Issue by carlosvivi2018** [iamadamdev/bypass-paywalls-chrome#485]
There is a message box saying that "Cookies on FT Sites" etc, then if clicked into the articles there will be paywall asking me to join membership. 

Others website works fine for me. Thanks for your help in advance!

**Comment by iscreamcoke** [comment]
Try to use the new version and see if the problem persists:
https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iscreamcoke** [comment]
Try using the new version and see if the problem persists:
https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by carlosvivi2018** [comment]
> Try using the new version and see if the problem persists:
> https://github.com/magnolia1234/bypass-paywalls-chrome-clean

Thanks. Did try the new version. It works on economists / Caixin Global (which the old version did not work) but unfortunately failed to pass the paywall of FT....

**Comment by magnolia1234** [comment]
Working just fine for me (BP's cookie-fix).
You can block the banner with 'I don't care about cookies'-extension (banner-class changed).

**Comment by iamadamdev** [comment]
Works fine for me, do you have uBlock Origin installed?

**Comment by jimmydeuxfois** [comment]
Use this extension instead: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

It supports way more websites, it's more regularly updated and it doesn't track you with Analytics

**Comment by llacb47** [comment]
stop shilling your repo

**Comment by jimmydeuxfois** [comment]
@laacb47 you're out of loop kid. Adam has just been accepting PRs and copying fixes from other repos for the last 5 months. You won't see any update this year as he banned all the big contributors.

just look at this: https://github.com/iamadamdev/bypass-paywalls-chrome/commits/master

**Comment by jimmydeuxfois** [comment]
@llacb47 you're out of the loop kid. Adam has just been accepting PRs and copying fixes from other repos for the last 5 months. You won't see any update this year as he banned all the big contributors.

just look at this: https://github.com/iamadamdev/bypass-paywalls-chrome/commits/master

**Comment by jimmydeuxfois** [comment]
@llacb47 you're out of the loop kid. Adam has just been accepting PRs and copying fixes from other repos for the last 5 months. You won't see any update this year as he banned all the big contributors.

just look at this: https://github.com/iamadamdev/bypass-paywalls-chrome/commits/master

**Comment by jimmydeuxfois** [comment]
@llacb47 you're out of the loop kid. Adam has just been clicking 'accept PR' and copying fixes from other repos for the last 5 months. You won't see any update this year as he banned all the big contributors.

just look at this: https://github.com/iamadamdev/bypass-paywalls-chrome/commits/master

**Comment by iamadamdev** [comment]
@jimmydeuxfois I spend my free time on this.. I take a break during Xmas and now I get 2 people shilling their own repo and they ripped it off mine. yeah, you're welcome for all the free time I put into this repo. I also thank all contributors to it.

**Comment by rsd1995** [comment]
@iamadamdev Dear Adam, 

I apologise on behalf of this community for our comments; you have provided us such a helpful tool to acquire information for free, saving all of us hundreds of pounds and affordably educating ourselves on current affairs that we wouldn't have been able to otherwise. So thank you very much for all your committed efforts. I have found the FT to work well for me - no apparent issues here from my side. The Economist on the other hand seems in need of a little tweeking. If you wouldn't mind attending to this, I (and I'm sure everyone here too) would be very grateful, and I'm sure everyone will love you as a result! I can't believe you only spend your free time on this! I would love to learn how to do this myself, so I can fix these issues manually and help chip in to solve the problems with you (and anyone else interested for that matter) and work together to help educate the community even more than our current level. Thank you very much for all your work, I hope you enjoyed a wonderful Xmas break and I wish you all the best. 

Kind regards,
Rishi

**Comment by iamadamdev** [comment]
@rsd1995 Thanks for the kind words. Btw did you try the latest release (yesterday)? The Economist should be working now.

**Comment by rsd1995** [comment]
@iamadamdev Adam, you are a genius - It's worked perfectly and all is fixed under the latest release! Thank you very much for fixing this problem, it's much appreciated. If there is any way I can send a donation, please let me know. Kind regards, Rishi

**Comment by joker327** [comment]
Indeed weird, it seems 'Mr. Genius' is still just copying commits from @magnolia1234 repo ...
