### ISSUE TITLE
Request to add website (telegram.com)

### ISSUE THREAD

**Issue by laxerlager** [iamadamdev/bypass-paywalls-chrome#488]
I kindly please request that www.telegram.com be added.

Thanks,
laxerlager

**Comment by iscreamcoke** [comment]
> Please Note: We are temporarily unavailable to users from certain countries while we upgrade our site to implement new methods for data processing as required by applicable laws.

I can't test the website sorry, telegram.com appears to be blocked in the EU (GDPR)

**Comment by magnolia1234** [comment]
Maybe set you VPN to USA?
Local news from Worcester, Massachusetts.
A block of TinyPass paywall-script will fix it.
Use https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
Stop trying to advertise your own repo on Bypass Paywalls. You didn't even credit me or the original 'Bypass Paywalls' in your repo.

**Comment by iscreamcoke** [comment]
Just look at the list of commits Adam... Today is literally the first commit/improvement you have pushed since September, 23rd (still based on someone else's PR though)

Nobody "ripped you off", you did it to yourself: the repo was already dependent on other contributors for months before it was eventually forked ('BP by Adam' should have rather been named 'BP by the contributors and sometimes by Adam'). And finally you let the extension's users alone with bugs during more than 1 month.

The new repo just fixes those issues and remove the sneaky Analytics tracking, that's all, no offence intended.

**Comment by iscreamcoke** [comment]
Just look at the list of commits Adam (which is also transparently displayed on the new repo)...

Today is literally the first commit/improvement you have pushed since September, 23rd (still based on someone else's PR though)

Nobody "ripped you off", you did it to yourself: the repo had already been depending on other contributors for months before it was eventually forked (did you credit all these contributors? The extensions should have been called 'BP by contributors' rather than 'BP by Adam-no commit in 4 months'). And finally you let the extension's users alone with bugs during more than 1 month.

The new repo just fixes those issues and remove the sneaky Analytics tracking, that's all, no offence intended.

**Comment by iscreamcoke** [comment]
But now that every party had said what he had been thinking about the (in-)actions of the other (though I'm not the public agent of Magnolia), we could eventually reach a common solution and maybe eventually merge the two repos for the good of everyone

**Comment by iscreamcoke** [comment]
But now that every party has said what he had been thinking about the (in-)actions of the other (though I'm not the 'official representative' of Magnolia), we could eventually reach a common solution and maybe eventually merge the two repos for the good of everyone

**Comment by iamadamdev** [comment]
You never mentioned you wanted credit in my repo. The least you could do is contact me before or credit me before trying to advertise your own repo in my space. Ever look at the timing? It's December, most people take a winter vacation, you can't expect me to keep updating during that time.

**Comment by iscreamcoke** [comment]
I would like to be able to take 1.5 months of vacation in winter too.. Anyway I don’t know what your plan is, but the repo is lagging behind magnolia’s version in terms of bug fixes/improvements and users won’t wait 1.5 months for a PR if they can have access to quicker and more reliable solution elsewhere.

**Comment by iamadamdev** [comment]
"I would like to be able to take 1.5 months of vacation in winter too"
Maybe you forgot I am not getting paid for doing this. I am doing this in my own time for FREE.
