### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by cantonalex** [iamadamdev/bypass-paywalls-chrome#567]
Would pay for Safari Support

**Comment by iamadamdev** [comment]
No plans at this time to port over for Safari.

**Comment by nwhobart** [comment]
Have these plans changed after WWDC and the [announcement](https://developer.apple.com/videos/play/wwdc2020/10665/) of the converter tool?

**Comment by billatq** [comment]
For fun, I played around with this because Apple brought this extensions API to iOS and it's possible to sideload such a thing with something like AltStore. Unfortunately, stuff is super broken, even with the converter tool.

You'd need a rewrite to be able to get the blocking functionality, and while you can rewrite pages, you can't do other things like such as set arbitrary HTTP headers. It looks like it may be possible to access cookies, but overall I think it would be a non-trivial rewrite and some things still wouldn't work.
