### ISSUE TITLE
Impossible to install on Firefox 75 on macOS Catalina

### ISSUE THREAD

**Issue by Neronerex** [iamadamdev/bypass-paywalls-chrome#610]
This add-on is impossible to install in Firefox 75 for macOS Catalina (No problems on Firefox for Windows 10).

Error while installing the update:

github.com
The add-on could not be downloaded because of a connection failure

**Comment by iamadamdev** [comment]
I'm still on Mojave so I can't test this. Does [v1.6.9](https://github.com/iamadamdev/bypass-paywalls-firefox/releases/download/v1.6.9/bypass_paywalls-1.6.9-an+fx.xpi) install fine?
Otherwise try downloading the source here in this repo, run build/build.sh and install the resulting xpi from there. Does that work?

**Comment by a-strange-octopus** [comment]
I'm on MacOS Catalina and I'm using Firefox 75. The add-on is working fine for me on the latest version
