### ISSUE TITLE
Users are getting logged out at Feedly.com

### ISSUE THREAD

**Issue by senlamy** [iamadamdev/bypass-paywalls-chrome#652]
Hello, this is Petr from Feedly. Our customers since Monday keep reporting that they're being logged out and that they see this error:

Error: 929 / Bug / Authenticated requests with no session

Can you please look into this? If you need further info from Feedly devs, let me know.

**Comment by iamadamdev** [comment]
Hi,
I need exact repro steps to try and fix it.
I created a free account on feedly and clicked around, closed the tab and opened another and went back to feedly.com and it kept me logged in.

**Comment by kimkha** [comment]
Thanks @senlamy. The owner of this extension is @iamadamdev . I also used feedly for months, with no issue.

**Comment by senlamy** [comment]
> Hi,
> I need exact repro steps to try and fix it.

Do you use latest Chrome?

**Comment by senlamy** [comment]
Also, can you follow some of the sites your extension supports? Like NYT Tech, Washpost tech, Atlantic Tech, Business Insider, MIT Tech review, Wired? Maybe they interact with your extension and cause the issue.

**Comment by senlamy** [comment]
Also make sure you're logging in via Google login method

**Comment by iamadamdev** [comment]
I used the Google login method. Btw if any of the sites are selected then it is expected for them to be logged out went navigating to those sites.

**Comment by senlamy** [comment]
It looks like the issue was with an older version of this extension. With 1.7.1. it works fine. I'll report back if I'll get a reproducible case with the latest extension.

**Comment by iamadamdev** [comment]
Glad to hear!

**Comment by kimkha** [comment]
Oh, I can guess it relates to the old issue that I resolved 😄

**Comment by kimkha** [comment]
Hey, I just repro it. Will look into it.

**Comment by kimkha** [comment]
Hey, @iamadamdev , I know why, but don't know how to fix properly.

When feedly.com load an image from supported sites (for example https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fs3-ap-northeast-1.amazonaws.com%2Fpsh-ex-ftnikkei-3937bb4%2Fimages%2F7%2F8%2F1%2F3%2F27243187-1-eng-GB%2FThai%20monkey.JPG?source=nar-cms&width=1024&height=512&fit=cover&gravity=faces), the extension will inject script:

https://github.com/iamadamdev/bypass-paywalls-chrome/blob/389a055dc9d058a505179263a74747fdcb7ec4db/src/js/background.js#L351-L353

The content script has:

https://github.com/iamadamdev/bypass-paywalls-chrome/blob/389a055dc9d058a505179263a74747fdcb7ec4db/src/js/contentScript.js#L1-L3

Which clear local storages of feedly.com. And that's why users are logged out.

**Comment by kimkha** [comment]
Okay, I just found a way to go around. Hope that fixes
