### ISSUE TITLE
New site request: [https://www.science-et-vie.com].

### ISSUE THREAD

**Issue by BeefTorpedo** [iamadamdev/bypass-paywalls-chrome#689]
Could you please add Science et vie [https://www.science-et-vie.com/].
Example article: "https://www.science-et-vie.com/science-et-culture/n-uds-une-etudiante-en-maths-resout-une-enigme-vieille-de-50-ans-56413".

Confirmed

**Comment by kimkha** [comment]
Doesn't sound like a paywalled article.

**Comment by BeefTorpedo** [comment]
> Doesn't sound like a paywalled article.

Sorry but I am ignorant as to why it doesn't seem to be paywalled? The website loads with the full text of the article and only after a second or two does the paywall appear. It's easier to see it with longer articles such as this one: "https://www.science-et-vie.com/corps-et-sante/therapie-genique-enfin-elle-soigne-56267".

**Comment by kimkha** [comment]
oh, right. I'm not so sure why the paywall didn't appear then. I saw it now. Let me see.

**Comment by kimkha** [comment]
Okay, should be bypassed after #693

**Comment by banikg** [comment]
I need some guidance on the below quote on adding new sites, as the below comment seems confusing.......
 " 7. If it loads without a paywall replace this entire template text with the word "Confirmed" and submit the request. Otherwise please do not submit an issue as this extension cannot bypass it either."
E.g. the site  https://www.science-et-vie.com/corps-et-sante/therapie-genique-enfin-elle-soigne-56267" loaded with paywall and i can see the request is getting submitted with "confirmed" and its in the process of getting bypass as of latest PR.. So, please help to clarify
.

**Comment by kimkha** [comment]
As @BeefTorpedo mentioned, it's successfully loaded without paywall few seconds before the paywall appear. That means "If it loads without a paywall"

**Comment by banikg** [comment]
okay... understood & thanks. At least, at my end it was difficult to catch that seconds gap. it was almost instant for me that why it triggers that confusion....
