### ISSUE TITLE
Is it possible to get this packaged as a userscript?

### ISSUE THREAD

**Issue by Invisible40** [iamadamdev/bypass-paywalls-chrome#772]
I don't have experience with this, but I use Tampermonkey for userscripts.  Can this be turned into a userscript, so we can avoid the developer mode popup?

**Comment by eastmarch** [comment]
If you use Chromium instead of Chrome, you can install the .crx package from the releases page. Only have to go to extensions page, enable developer mode, refresh page (!) and then drag-and-drop the extension. No popups afterwards. This page has the installers: https://chromium.woolyss.com // Recommend the first one by Hibbiki.

**Comment by Invisible40** [comment]
Right now I'm using Brave, but I'll try it out. Thanks!
