### ISSUE TITLE
Why isn't the option to add custom sites available for Firefox?

### ISSUE THREAD

**Issue by mfelice** [iamadamdev/bypass-paywalls-chrome#785]
What is the reason for not having this option? 
Do you plan to add it in the future?

Thanks!

**Comment by iamadamdev** [comment]
Because the more privacy-conscious users use Firefox and don't want the extension to have <all_urls> permission which would be needed for custom sites. But it's not too hard to modify the code yourself and enable custom sites on Firefox.

**Comment by bob-kiefer** [comment]
Do you also have a DIY instruction for the regular user to edit the permissions, build an unsigned add-on and then install it in Firefox (not possible on desktop) ...?

**Comment by unbeatable-101** [comment]
I don’t know if you saw this, but here is what he said:

UPDATE:
I'm writing this answer here because I do not have permission to reply to @iamadamdev's comment:

More privacy-conscious users use Firefox and don't want the extension to have the <all_urls> permission which would be needed for custom sites. But it's not too hard to modify the code yourself and enable custom sites on Firefox.
I don't know much about extension development so I had a look at the issue you mention online. From what I understand, you would need to enable <all_urls> permission because you don't know in advance what URLs the users will add in the future, right? It seems this can be avoided by enabling sites on a case-by-case basis at runtime:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions

Would that help?
