### ISSUE TITLE
Jota.info

### ISSUE THREAD

**Issue by esteves023** [iamadamdev/bypass-paywalls-chrome#86]
Is it possible to implement this website: https://www.jota.info

It used to have a regular paywall and easy to bypass. Now they've implemented some kind of redirecting script which redirects any article/page to "https://www.jota.info/?pagename=paywall&redirect_to=" before the regular page link and asks to sign up to read 10 free articles. No idea if it's a hard paywall.

**Comment by iamadamdev** [comment]
You can see if it's a hard paywall by following these instructions:

Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.

**Comment by iamadamdev** [comment]
It's a hard paywall.
