### ISSUE TITLE
Is there any chance to work on cn.wsj.com and http://www.caixin.com/

### ISSUE THREAD

**Issue by bush911** [iamadamdev/bypass-paywalls-chrome#939]
Thanks for this amazing tool.
please support both cn.wsj.com and caixin.com

**Comment by iamadamdev** [comment]
New site requests - Before submitting an issue please read the following:
Only large or major sites will be considered. Usually premium articles cannot be bypassed as they are behind a hard paywall.

Install the uBlock Origin extension if it hasn't been installed already. See if you are still getting a paywall.
Check if using Cookie Remover can bypass the paywall. If not, continue to the next step.
First search 'Issues' to see if the site has been requested already.
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new incognito window (Ctrl+Shift+N on Chrome) or Private window (Ctrl+Shift+P on Firefox), and paste the article title into Google.
Click on the same article from the Google search results page.
If it loads without a paywall replace this entire template text with the word "Confirmed" and submit the request. Otherwise please do not submit an issue as this extension cannot bypass it either.
