### ISSUE TITLE
Some articles on Bloomberg not unblocked

### ISSUE THREAD

**Issue by aksingh11** [iamadamdev/bypass-paywalls-chrome#97]
Hello ,
this link somehow doesn't work . ( https://www.bloomberg.com/news/articles/2014-11-06/india-vs-dot-china-the-battle-for-global-manufacturing )
I tried using unlock along with the the bypass paywalls extension. Please advise if I need to do do something extra .
thanks -

**Comment by iamadamdev** [comment]
Won't work for premium articles. You can test this by:

Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.
